/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.typesafe.config.*;
import akka.actor.*;

public class App {

    public static void main(String[] args) {        
        Config conf = ConfigFactory.load();
        System.out.println("The answer is: " + conf.getString("simple-app.answer"));

        final ActorSystem system = ActorSystem.create();
        System.out.println(system.settings());
        system.terminate();
    }
}
